version: "3.9"
services:

  db:
    image: postgres:13.4
    container_name: postgres
    env_file:
      - movies_admin/.env
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: web
    env_file:
      - movies_admin/.env
    depends_on:
      - db
    volumes:
      - ./static/:/static/:ro
    command:
      - nostatic

  etl:
    build: ./postgres_to_es
    container_name: etl
    depends_on:
      - elasticsearch
      - web

  nginx:
    build: ./nginx
    container_name: my-nginx
    depends_on:
      - web
    volumes:
      - ./static:/data/static:ro
    ports:
      - "80:80"

  kibana:
    container_name: kib01-test
    image: docker.elastic.co/kibana/kibana:7.7.0
    ports:
      - 5601:5601

  elasticsearch:
    container_name: es01-test
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
volumes:
  data:
    driver: local
