version: '2'
services:
  kibana:
    container_name: kib01-test
    image: docker.elastic.co/kibana/kibana:7.7.0
    ports:
      - 5601:5601
#    volumes:
#      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - elastic
  elasticsearch:
    container_name: es01-test
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic
volumes:
  data:
    driver: local
networks:
  elastic:
    driver: bridge
